# role: mysql

- name: Load needed paths
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: Install mysql packages (mysql)
  action: apt pkg={{item}} state=installed
  with_items:
       - mysql-server
       - mysql-client
       - libdbi-perl
       - python-mysqldb

- name: Add anonymous mysql user
  mysql_user:
    name: anonymous
    host: "%"
    priv: '*.*:SELECT'
    state: present

- name: Bind to external ip
  ini_file:
    dest: "{{ mysql_config }}"
    section: mysqld
    option: "bind-address"
    value: "0.0.0.0"
  notify: Restart-Mysql

- name: innodb_file_per_table
  ini_file:
    dest: "{{ mysql_config }}"
    section: mysqld
    option: "innodb_file_per_table"
    value: "ON"
  notify: Restart-Mysql

- name: Mount the mysql volume
  mount:
    src: /dev/vdb
    path: /mnt
    fstype: ext4
    state: mounted
    
- name: Ensure database files are owned by mysql
  file:
    path: /mnt
    owner: mysql
    group: mysql
    recurse: yes
    state: directory

- name: Symlink the database files
  shell: ln -s /mnt/* .
  args:
    chdir: /var/lib/mysql
  ignore_errors: yes
  notify: Restart-Mysql
