# role: tark

- name: Create the directory for tark
  file:
    path: /opt/tark
    state: directory
    mode: 0755
    owner: "{{ vm_username }}"
    group: "{{ vm_username }}"

- name: See if TaRK git repo exists
  stat:
    path: /opt/tark/tark_app
  register: tark_repo_dir

- name: Fetch TaRK git repo
  become: false
  git:
    repo: "https://github.com/lairdm/tark_ui.git"
    dest: /opt/tark/tark_app
    version: master
    clone: yes
  when: not tark_repo_dir.stat.exists

- name: Tune config for mod_faidx
  lineinfile:
    dest: "{{ item.file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - { file: "/opt/tark/tark_app/tark_rest/settings/base.py", regexp: '^SEQ_HOST_URI.*', line: "SEQ_HOST_URI = 'http://haproxy/faidx/'" }
    - { file: "/opt/tark/tark_app/tark_rest/urls.py", regexp: '.*tark.urls.*', line: "    url(r'^', include('tark.urls'))" }
    
- name: Create TaRK virtualenv
  become: false
  pip:
    requirements: /opt/tark/tark_app/requirements.txt
    virtualenv: /opt/tark/env

- name: Copy wsgi script to tark
  copy:
    src: tark.wsgi
    dest: /opt/tark/tark_app/tark.wsgi
    owner: www-data
    group: www-data
    mode: 0755

- name: Copy tark virtual host config
  copy:
    src: tark.conf
    dest: /etc/apache2/sites-available/tark.conf
    owner: root
    group: root
    mode: 744

- name: Activate tark vhost
  command: "a2ensite {{ item }}"
  with_items:
    - tark
  notify: Restart-Apache
    
- name: Activate wsgi module
  apache2_module:
    state: present
    name: wsgi
  notify: Restart-Apache

- name: Activate headers module
  apache2_module:
    state: present
    name: headers
  notify: Restart-Apache

# Using the default anonymous user, there is no
# secret here.
- name: Move secrets files in to app
  copy:
    src: secrets.py
    dest: /opt/tark/tark_app/tark_rest/settings/secrets.py
    owner: www-data
    group: www-data
    mode: 0644

- name: Setup Swagger UI
  include: swagger.yml

